# Generated by Django 6.0.6 on 2026-07-03 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('constraint_type', models.CharField(choices=[('ROOM_TYPE_REQUIRED', 'Room Type Required'), ('MAX_DAILY_HOURS', 'Max Daily Hours'), ('NO_ADJACENT_GAPS', 'No Adjacent Gaps'), ('CUSTOM', 'Custom Rule')], max_length=50)),
                ('target_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('SECTION', 'Section'), ('ROOM', 'Room'), ('SUBJECT', 'Subject'), ('GLOBAL', 'Global / Semester')], max_length=20)),
                ('is_hard', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Weight for soft constraints')),
                ('max_daily_periods', models.PositiveIntegerField(blank=True, help_text='Used for MAX_DAILY_HOURS', null=True)),
                ('required_room_type', models.CharField(blank=True, choices=[('LECTURE', 'Lecture'), ('LAB', 'Laboratory'), ('SEMINAR', 'Seminar'), ('COMPUTER_LAB', 'Computer Lab')], help_text='Used for ROOM_TYPE_REQUIRED', max_length=20, null=True)),
                ('custom_parameters', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='core.semester')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('period_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'period_number'],
                'unique_together': {('day_of_week', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='academics.teacherprofile')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='scheduling.timeslot')),
            ],
            options={
                'verbose_name_plural': 'Teacher availabilities',
                'unique_together': {('teacher', 'timeslot')},
            },
        ),
    ]
