# Generated by Django 6.0.6 on 2026-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='max_consecutive_periods',
            field=models.PositiveIntegerField(blank=True, help_text='Used for MAX_CONSECUTIVE_PERIODS', null=True),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('ROOM_TYPE_REQUIRED', 'Room Type Required'), ('MAX_DAILY_HOURS', 'Max Daily Hours'), ('NO_ADJACENT_GAPS', 'No Adjacent Gaps'), ('MAX_CONSECUTIVE_PERIODS', 'Max Consecutive Periods'), ('PREFERRED_TEACHING_TIME', 'Preferred Teaching Time'), ('CUSTOM', 'Custom Rule')], max_length=50),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='custom_parameters',
            field=models.JSONField(blank=True, help_text='Used for PREFERRED_TEACHING_TIME and CUSTOM. Preferred teaching time shape: {"preferred_days": [1, 2], "period_start": 1, "period_end": 4} where preferred_days uses TimeSlot day codes (1=Monday … 5=Friday).', null=True),
        ),
    ]
