# Generated by Django 6.0.6 on 2026-07-23 16:34

from django.db import migrations, models


def delete_custom_constraints(apps, schema_editor):
    Constraint = apps.get_model('scheduling', 'Constraint')
    Constraint.objects.filter(constraint_type='CUSTOM').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_constraint_course_level'),
    ]

    operations = [
        migrations.RunPython(delete_custom_constraints, migrations.RunPython.noop),
        migrations.AddField(
            model_name='constraint',
            name='max_weekly_periods',
            field=models.PositiveIntegerField(blank=True, help_text='Used for MAX_WEEKLY_HOURS', null=True),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('ROOM_TYPE_REQUIRED', 'Room Type Required'), ('MAX_DAILY_HOURS', 'Max Daily Hours'), ('MAX_WEEKLY_HOURS', 'Max Weekly Hours'), ('NO_ADJACENT_GAPS', 'No Adjacent Gaps'), ('MAX_CONSECUTIVE_PERIODS', 'Max Consecutive Periods'), ('PREFERRED_TEACHING_TIME', 'Preferred Teaching Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='custom_parameters',
            field=models.JSONField(blank=True, help_text='Used for PREFERRED_TEACHING_TIME. Shape: {"preferred_days": [1, 2], "period_start": 1, "period_end": 4} where preferred_days uses TimeSlot day codes (1=Monday … 5=Friday).', null=True),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='weight',
            field=models.PositiveIntegerField(default=10, help_text='Internal soft-constraint weight (always 10).'),
        ),
    ]
