# Generated by Django 6.0.6 on 2026-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('CLASS_REP', 'Class Representative')], default='ADMIN', max_length=20),
        ),
    ]
