# Generated by Django 6.0.6 on 2026-07-26 10:58

import accounts.models
from django.db import migrations, models


def grant_superusers(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_superuser=True).update(can_create_admins=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_school_nullable'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.TimeForgeUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_admins',
            field=models.BooleanField(default=False, help_text='If ticked, this admin may create other admin accounts.'),
        ),
        migrations.RunPython(grant_superusers, migrations.RunPython.noop),
    ]
