# Generated by Django 6.0.6 on 2026-07-03 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-incremented per semester. Version 1 is the first generation.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('penalty_score', models.IntegerField(default=0, help_text='Soft-constraint penalty score returned by the scheduling engine.')),
                ('notes', models.TextField(blank=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='core.semester')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['-version'],
                'unique_together': {('semester', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, help_text='If True, re-generation will not overwrite this slot (Prompt 13).')),
                ('is_manual', models.BooleanField(default=False, help_text='If True, this slot was moved by the drag-and-drop editor.')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='academics.classsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='core.room')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='academics.teacherprofile')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='scheduling.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'ordering': ['timeslot__day_of_week', 'timeslot__period_number'],
                'unique_together': {('timetable', 'timeslot', 'class_session'), ('timetable', 'timeslot', 'room')},
            },
        ),
    ]
