# Generated by Django 6.0.6 on 2026-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['timetable', 'teacher'], name='timetable_t_timetab_ae07fb_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['timetable', 'room'], name='timetable_t_timetab_d3cc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['timetable', 'timeslot'], name='timetable_t_timetab_a848ca_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['timetable', 'class_session'], name='timetable_t_timetab_fcb2f5_idx'),
        ),
    ]
