# Generated by Django 6.0.6 on 2026-07-14 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('timetable', '0002_timetableslot_timetable_t_timetab_ae07fb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_discarded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_change_sets', to='timetable.timetable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='timetable.draftchangeset')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_moves', to='timetable.timetableslot')),
                ('target_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('target_timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
            ],
            options={
                'unique_together': {('change_set', 'slot')},
            },
        ),
    ]
