# Generated by Django 6.0.6 on 2026-07-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classrepprofile'),
        ('core', '0004_require_school_on_core_models'),
        ('scheduling', '0002_constraint_max_consecutive_periods_and_more'),
        ('timetable', '0004_timetable_published_at_timetable_published_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('timetable', 'timeslot', 'class_session'), ('timetable', 'timeslot', 'room'), ('timetable', 'timeslot', 'teacher')},
        ),
        migrations.CreateModel(
            name='TimetableEditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timetable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_lock', to='timetable.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Edit Lock',
                'verbose_name_plural': 'Timetable Edit Locks',
            },
        ),
    ]
