# Generated by Django 6.0.6 on 2026-07-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classrepprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_visiting',
            field=models.BooleanField(default=False, help_text='Tick if this is visiting / guest faculty.'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('Prof. Dr.', 'Prof. Dr.'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Dr.', 'Dr.'), ('Lecturer', 'Lecturer'), ('Assistant Lecturer', 'Assistant Lecturer')], max_length=50),
        ),
    ]
