# Generated by Django 6.0.6 on 2026-07-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_course_courselevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='max_hours_per_week',
        ),
    ]
