# Generated by Django 6.0.6 on 2026-07-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_custom_add_max_weekly_hours'),
        ('core', '0005_course_session_restructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevelOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (7am–2pm)'), ('DAY', 'Day (9am–5pm)')], default='DAY', max_length=10)),
                ('course_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.courselevel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_level_offerings', to='core.session')),
            ],
            options={
                'ordering': ['course_level__course__name', 'course_level__level'],
                'unique_together': {('session', 'course_level')},
            },
        ),
    ]
