# Generated by Django 6.0.6 on 2026-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_rename_max_hours_per_day_to_max_periods_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseleveloffering',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning (7am–2pm)'), ('DAY', 'Day (9am–4pm)')], default='DAY', max_length=10),
        ),
    ]
